# Generated by Django 5.2.11 on 2026-09-28 15:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='schedule_occurrence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PreventiveSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('kind', models.CharField(choices=[('Preventive', 'Preventive'), ('Inspection', 'Inspection')], default='Preventive', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('cadence', models.CharField(choices=[('Daily', 'Every day'), ('Weekly', 'Every week'), ('Monthly', 'Every month'), ('Yearly', 'Every year')], default='Daily', max_length=12)),
                ('run_time', models.TimeField(default='09:00')),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month_of_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('create_days_before', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('next_run_date', models.DateField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventive_schedules', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventive_schedules', to='cmms.component')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_preventive_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['enabled', 'next_run_date', 'title'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='preventive_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_work_orders', to='cmms.preventiveschedule'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('preventive_schedule__isnull', False), ('schedule_occurrence_date__isnull', False)), fields=('preventive_schedule', 'schedule_occurrence_date'), name='unique_preventive_schedule_occurrence'),
        ),
    ]
