# Generated by Django 5.2.11 on 2026-09-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0003_workorder_schedule_occurrence_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiveschedule',
            name='excluded_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='preventiveschedule',
            name='excluded_days_of_month',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='preventiveschedule',
            name='excluded_months',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='preventiveschedule',
            name='excluded_weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
